// Code generated by MockGen. DO NOT EDIT.
// Source: todo-lists/core (interfaces: IRepo)

// Package core is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"
	entity "todo-lists/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockIRepo is a mock of IRepo interface.
type MockIRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIRepoMockRecorder
}

// MockIRepoMockRecorder is the mock recorder for MockIRepo.
type MockIRepoMockRecorder struct {
	mock *MockIRepo
}

// NewMockIRepo creates a new mock instance.
func NewMockIRepo(ctrl *gomock.Controller) *MockIRepo {
	mock := &MockIRepo{ctrl: ctrl}
	mock.recorder = &MockIRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepo) EXPECT() *MockIRepoMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockIRepo) CreateTask(arg0 *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockIRepoMockRecorder) CreateTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockIRepo)(nil).CreateTask), arg0)
}

// DeleteTask mocks base method.
func (m *MockIRepo) DeleteTask(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockIRepoMockRecorder) DeleteTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockIRepo)(nil).DeleteTask), arg0)
}

// FilterTasksByDeadline mocks base method.
func (m *MockIRepo) FilterTasksByDeadline(arg0, arg1 time.Time) ([]entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterTasksByDeadline", arg0, arg1)
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterTasksByDeadline indicates an expected call of FilterTasksByDeadline.
func (mr *MockIRepoMockRecorder) FilterTasksByDeadline(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterTasksByDeadline", reflect.TypeOf((*MockIRepo)(nil).FilterTasksByDeadline), arg0, arg1)
}

// GetAllTasks mocks base method.
func (m *MockIRepo) GetAllTasks() ([]entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTasks")
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTasks indicates an expected call of GetAllTasks.
func (mr *MockIRepoMockRecorder) GetAllTasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTasks", reflect.TypeOf((*MockIRepo)(nil).GetAllTasks))
}

// GetTaskById mocks base method.
func (m *MockIRepo) GetTaskById(arg0 int) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskById", arg0)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskById indicates an expected call of GetTaskById.
func (mr *MockIRepoMockRecorder) GetTaskById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskById", reflect.TypeOf((*MockIRepo)(nil).GetTaskById), arg0)
}

// GetTasksByTag mocks base method.
func (m *MockIRepo) GetTasksByTag(arg0 string) ([]entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByTag", arg0)
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByTag indicates an expected call of GetTasksByTag.
func (mr *MockIRepoMockRecorder) GetTasksByTag(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByTag", reflect.TypeOf((*MockIRepo)(nil).GetTasksByTag), arg0)
}

// SearchTasksByName mocks base method.
func (m *MockIRepo) SearchTasksByName(arg0 string) ([]entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTasksByName", arg0)
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTasksByName indicates an expected call of SearchTasksByName.
func (mr *MockIRepoMockRecorder) SearchTasksByName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTasksByName", reflect.TypeOf((*MockIRepo)(nil).SearchTasksByName), arg0)
}

// UpdateTask mocks base method.
func (m *MockIRepo) UpdateTask(arg0 *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockIRepoMockRecorder) UpdateTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockIRepo)(nil).UpdateTask), arg0)
}
